
site_name: GraphiQ
site_description: GraphiQ
#site_url: http://0.0.0.0:8000

use_directory_urls: false  # good for opening HTML files directly, but should be 'true' for deployment

nav:
  - Introduction: index.md
  - Tutorials:
      - Getting started: tutorials.md
      - Example notebook: simulate_circuit.ipynb
  - How to guides: how-to-guides.md
  - Reference:
      - Overview: reference.md
      - States: reference/states.md
      - Circuits: reference/circuit.md
      - Backends: reference/backends.md
      - Solvers: reference/solvers.md
      - Noise: reference/noise.md
      - Metrics: reference/metrics.md
  - Explanation: explanation.md



theme:
  name: material

#  logo: img/oqd-logo.png

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: light-blue
    accent: orange
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: light-blue
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

  features:
  - search.suggest
  - search.highlight
#  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
#  - navigation.tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: yes
  - mkdocs-jupyter:
      ignore_h1_titles: True


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 1
      title: "Table of contents"

  # for code snippets/syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # for notes/admonitions
  - admonition
  - pymdownx.details

#  # for flow diagrams
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js