[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "graphiq"
version = "0.0.4"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "networkx",
    "matplotlib",
    "tqdm",
    "seaborn",
    "scipy",
    "flask",
]
readme = "README.md"
keywords = ["quantum", "photonic", "circuit", "design"]
license = {text = "Apache 2.0"}
authors = [
    {name = "Benjamin MacLellan", email = "benjamin@ki3photonics.com"},
    {name = "Jie Lin", email = "jie@qbt.io"},
    {name = "Sohban Ghanbari", email = "sohban@qbt.io"},
]
classifiers = [
    "Programming Language :: Python :: 3",
]


[project.optional-dependencies]
jax = ["jax", "optax"]
ray = ["ray", "pandas"]
qiskit = ["qiskit"]
all = ["jax", "optax", "ray", "pandads", "qiskit"]