name: Codecov

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codecov

      - name: Run tests and generate coverage report
        run: |
          coverage run --source=. -m pytest
          coverage report -m > coverage.txt

      - name: Upload coverage report to Codecov
        run: codecov --token=${{ secrets.CODECOV_TOKEN }}

